api:
  actions:
    - action: calibrate_co2_value
      variables:
        co2_ppm: int
      then:
        - scd4x.perform_forced_calibration:
            value: !lambda "return co2_ppm;"
            id: scd40
    - action: set_ambient_pressure
      variables:
        pressure_mbar: int
      then:
        - lambda: "id(scd40)->set_ambient_pressure_compensation(pressure_mbar);"

sensor:
  - platform: scd4x
    i2c_id: bus_a
    id: scd40
    measurement_mode: low_power_periodic    
    co2:
      name: "CO2"
      id: "co2"
      filters:
        - or:
          - delta: 5%
          - delta: 5      
    automatic_self_calibration: false
    ambient_pressure_compensation_source: dps310pressure
    temperature:
      name: "SCD40 Temperature"
      id: scd40_temperature
      disabled_by_default: true
      filters:
        - lambda: return x - id(scd40_temperature_offset).state;
    humidity:
      name: "SCD40 Humidity"
      id: scd40_humidity
      disabled_by_default: true
      filters:
        - lambda: return x - id(scd40_humidity_offset).state;

button:
    - platform: template
      name: "Calibrate CO2"
      id: calibrate_scd40
      entity_category: config
      on_press:
        - scd4x.perform_forced_calibration:
            value: 419
            id: scd40
number:
  - platform: template
    name: SCD40 Humidity Offset
    id: scd40_humidity_offset
    restore_value: true
    initial_value: 0
    min_value: -70.0
    max_value: 70.0
    entity_category: "CONFIG"
    unit_of_measurement: "%"
    optimistic: true
    update_interval: never
    step: 0.1
    mode: box
    disabled_by_default: true
  - platform: template
    name: SCD40 Temperature Offset
    id: scd40_temperature_offset
    restore_value: true
    initial_value: 18.86
    min_value: -70.0
    max_value: 70.0
    entity_category: "CONFIG"
    unit_of_measurement: "°C"
    optimistic: true
    update_interval: never
    step: 0.1
    mode: box
    disabled_by_default: true
